import React from 'react';
import { PatientData, OrganRisk } from '../../types/patient';
import { generateRecommendations } from '../../ai/recommendations';
import RecommendationCard from './RecommendationCard';

interface HealthRecommendationsProps {
  patientData: PatientData;
  organRisk: OrganRisk;
}

const HealthRecommendations: React.FC<HealthRecommendationsProps> = ({ patientData, organRisk }) => {
  const recommendations = generateRecommendations(patientData, organRisk);
  
  const highPriorityCount = recommendations.filter(r => r.priority === 'high').length;
  const mediumPriorityCount = recommendations.filter(r => r.priority === 'medium').length;
  const lowPriorityCount = recommendations.filter(r => r.priority === 'low').length;

  return (
    <div className="max-w-6xl mx-auto p-6">
      <div className="health-card mb-8">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-foreground mb-4">
            Personalized Health Recommendations
          </h2>
          <p className="text-muted-foreground mb-6">
            AI-powered recommendations tailored to your health profile and risk factors
          </p>
          
          {/* Summary Statistics */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
            <div className="bg-red-50 dark:bg-red-900/20 rounded-lg p-4">
              <div className="text-2xl font-bold text-red-600 dark:text-red-400">{highPriorityCount}</div>
              <div className="text-sm text-red-700 dark:text-red-300">High Priority</div>
            </div>
            <div className="bg-orange-50 dark:bg-orange-900/20 rounded-lg p-4">
              <div className="text-2xl font-bold text-orange-600 dark:text-orange-400">{mediumPriorityCount}</div>
              <div className="text-sm text-orange-700 dark:text-orange-300">Medium Priority</div>
            </div>
            <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-4">
              <div className="text-2xl font-bold text-green-600 dark:text-green-400">{lowPriorityCount}</div>
              <div className="text-sm text-green-700 dark:text-green-300">Low Priority</div>
            </div>
          </div>
        </div>

        {/* Recommendations Grid */}
        <div className="space-y-6">
          {recommendations.map((recommendation) => (
            <RecommendationCard
              key={recommendation.id}
              recommendation={recommendation}
            />
          ))}
        </div>

        {/* Disclaimer */}
        <div className="mt-8 p-6 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800">
          <div className="flex items-start space-x-3">
            <span className="text-blue-500 text-xl">ℹ️</span>
            <div>
              <h4 className="font-semibold text-blue-900 dark:text-blue-100 mb-2">
                Important Medical Disclaimer
              </h4>
              <p className="text-sm text-blue-800 dark:text-blue-200 leading-relaxed">
                These recommendations are generated by AI based on your health data and are for informational purposes only. 
                They do not constitute medical advice, diagnosis, or treatment. Always consult with qualified healthcare 
                professionals before making any changes to your health regimen, especially for high-priority recommendations. 
                Your doctor can provide personalized guidance based on your complete medical history and current health status.
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 mt-8 justify-center">
          <button className="px-6 py-3 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors">
            Export Recommendations as PDF
          </button>
          <button className="px-6 py-3 border border-border rounded-lg font-medium hover:bg-accent transition-colors">
            Share with Healthcare Provider
          </button>
          <button className="px-6 py-3 border border-border rounded-lg font-medium hover:bg-accent transition-colors">
            Set Reminders
          </button>
        </div>
      </div>
    </div>
  );
};

export default HealthRecommendations;

